name: Update Properties

on:
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  update-properties:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: "11"

      - name: Update properties
        run: ./mvnw --batch-mode versions:update-properties

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "build: update maven properties"
          title: "chore(deps): update maven properties"
          branch: update-properties
          delete-branch: true
